[pytest]
pythonpath = .

# Опции командной строки
addopts = -v --strict-markers --cov=src

# Где искать тесты
testpaths = tests

markers =
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети)